#------------------------------------------------------------------------------#
# Build Config
#------------------------------------------------------------------------------#

configfile:
  - config/config_hmpxv1.yaml # Load the default configuration
  - profiles/hmpxv1_nextstrain/builds.yaml # Load custom inputs, builds, and rule params

#------------------------------------------------------------------------------#
# Snakemake config
#------------------------------------------------------------------------------#

restart-times: 1
max-jobs-per-second: 1
latency-wait: 10
keep-going: True
show-failed-logs: True
rerun-incomplete: True
printshellcmds: False

#------------------------------------------------------------------------------#
# System config
#------------------------------------------------------------------------------#

# Maximum number of jobs to run
cores: 1
jobs : 1

# Default resources for a SINGLE JOB
default-resources:
  - cpus=1
  - mem_mb=4000
  - time_min=60
